config/routes.rb
Rails.application.routes.draw do
  # 透過 devise 實現使用者註冊，登入，管理
  devise_for :users

  # 前台餐廳 routes
  resources :restaurants, only: [:index, :show] do
    # for 餐廳評論
    resources :comments, only: [:create, :destroy]

    collection do
      # 瀏覽所有餐廳的最新動態
      get :feeds

      # TOP 10 Ranking restaurants
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end

    # 收藏與取消收藏餐廳功能
    member do
      post :favorite
      post :unfavorite
    end

  end

  root "restaurants#index"

  resources :categories, only: [:show]

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end

  # for 追蹤記錄，followships#create, followships#destroy
  resources :followships, only: [:create, :destroy]

  # for 交友記錄
  resources :friendships, only: [:create, :destroy]

  # 後台 routes
  namespace :admin, path: "akjdhkajsdh" do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # A restaurant belongs to specific category.
  belongs_to :category

  # A restaurant has_many comments.
  # 當 restaurant 物件被刪除時，同時刪除依賴的 comments
  has_many :comments, dependent: :destroy

  # 餐廳被很多使用者收藏，餐廳有很多收藏者
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  # 設定 name 欄位爲必填
  validates_presence_of :name

  # 掛載 carrierwave upload for upload image
  mount_uploader :image, PhotoUploader

  # for favorite restaurant check
  def is_favorited?(user)
    # 如果這家餐廳有被該使用者收藏，回傳 True
    self.favorited_users.include?(user)
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseAdminController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    # @restaurants = Restaurant.all
    # use Kaminari
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "Restaurant was successfully created."
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "Restaurant was failed to create!"
      render :new
    end
  end

  def show
    # 將此段程式碼另外宣告成 private method : find_restaurant
    # @restaurant = Restaurant.find(params[:id])
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "Restaurant data was successfully updated."
      redirect_to admin_restaurant_path(@restaurant.id)
    else
      flash.now[:alert] = "Restaurant was failed to update!"
      render :edit
    end
  end

  def destroy
    flash[:alert] = "#{@restaurant.name} was deleted!"
    @restaurant.destroy
    redirect_to admin_restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    # 新增使用者評論
    @comment = Comment.new
  end

  # for 所有餐廳的最新動態
  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  # for 每間餐廳的 dashboard (儀表板)
  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  # 收藏餐廳與取消收藏餐廳
  ## POST /restaurant/:id/favorite
  def favorite
    @restaurant = Restaurant.find(params[:id])

    # Rails 會判斷需要的外鍵資訊
    @restaurant.favorites.create!(user: current_user)
    # 上一行結果與 @restaurant.favorites.create!(user_id: current_user.id) 結果一致

    # 導回上一頁
    redirect_back(fallback_location: root_path)
  end

  ## POST /restaurant/:id/unfavorite
  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant_id: @restaurant.id, user_id: current_user.id)
    # favorites = Favorite.where(restaurant: @restaurant, user: current_user)

    favorites.destroy_all

    redirect_back(fallback_location: root_path)
  end

  # for TOP 10 人氣餐廳
  ## GET /restaurants/ranking
  def ranking
    # 用 favorites_count 升冪排序，只取前十筆
    @restaurants = Restaurant.order(favorites_count: :desc).first(10)
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/admin/restaurants/_form.html.erb
<div class="container">

  <!-- 欄位錯誤訊息提示 -->
  <% if @restaurant.errors.any? %>
    <h2>Oops! We need fix something here：</h2>
    <ul>
      <% @restaurant.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
    <hr>
  <% end %>

  <%= form_for [:admin, @restaurant] do |f| %>
    <div class="form-group">
      <%= f.collection_select(
        # :restaurant,
        :category_id,
        Category.all,
        :id,
        :name,
        {prompt: true},
        {class: "form-control"}
        ) %>

    </div>

    <div class="form-group">
      <%= f.label :name, "Name" %>
      <%= f.text_field :name, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :tel, "Tel" %>
      <%= f.text_field :tel, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :address, "Address" %>
      <%= f.text_field :address, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :opening_hours, "Opening Hours" %>
      <%= f.text_field :opening_hours, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :description, "Description" %>
      <%= f.text_field :description, class:"form-control" %>
    </div>

    <div class="form-group">
      <%= f.label :image, "Photo" %>

      <div class="clearfix"></div>

      <% if @restaurant.image? %>
        <div class="col-md-4">
          <!-- 讓圖片能隨著瀏覽器大小變化，置中 -->
          <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
        </div>
      <% end %>

      <%= f.file_field :image %>

    </div>

    <div class="clearfix"></div>

    <hr>
    <%= f.submit class: "btn btn-primary" %>

    <%= link_to "Cancel", admin_restaurants_path, class: "btn btn-default" %>

  <% end %>

</div>

app/views/admin/restaurants/edit.html.erb
<div class="container">
  <h2>編輯餐廳資料</h2>
</div>

<%= render partial: "form" %>

app/views/admin/restaurants/index.html.erb
<div class="container">

  <h1>餐廳後台</h1>

  <div>
    <%= link_to 'New Restaurant', new_admin_restaurant_path, class: "btn btn-primary" %>
  </div>

  <br>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <th>Restaurant ID</th>
        <th>Category</th>
        <th>Name</th>
        <th>Action</th>
      </tr>
    </thead>

    <tbody>
      <% @restaurants.each do |restaurant| %>
      <tr>
        <!-- 這邊教材用 th 的理由應該是要自動變粗體 -->
        <td><%= restaurant.id %></td>
        <td><%= restaurant.category.name %></td>
        <td><%= restaurant.name %></td>
        <td>
          <%= link_to 'Show', admin_restaurant_path(restaurant) %>
          <%= link_to 'Edit', edit_admin_restaurant_path(restaurant) %>
          <%= link_to 'Delete', admin_restaurant_path(restaurant), method: :delete, data: { confirm: "Are you sure?"} %>
        </td>
      </tr>
      <% end %>
    </tbody>

  </table>

  <div class="text-center">
    <!-- paginate 是kaminari的hepler，可以幫我們產出分頁按鈕的html -->
    <%= paginate @restaurants %>
  </div>

</div>

app/views/admin/restaurants/new.html.erb
<div class="container">
  <h2>建立新餐廳</h2>
</div>

<%= render partial: "form" %>

app/views/admin/restaurants/show.html.erb
<div class="container">
  <div class="row">

    <!-- 要加上 .col-md-12才能跟 col-md-4 切齊 -->
    <div class="col-md-12">
      <div class="col-md-4 text-center">
        <h1><%= @restaurant.name%></h1>
        <h3><%= @restaurant.category.name %></h3>
      </div>

    </div>

    <div class="col-md-4">
      <!-- 讓圖片能隨著瀏覽器大小變化，置中 -->
      <!-- 不過發現高度被限死的樣子，長度有跟著視窗改變大小，但是高度沒有。 -->
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <hr>

      <div class="well">
        <ul class="list-unstyled">
          <li>Opening Hours:<%= @restaurant.opening_hours %></li>
          <li>Tel: <%= @restaurant.tel %></li>
          <li>Address: <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>

    <div class="col-md-8">
      <%= @restaurant.description %>
    </div>

    <!-- 用 clearfix， 讓 回到首頁的按鈕 在比較理想的位置 -->
    <div class="clearfix"></div>

    <div class="col-md-12">
      <hr>
      <%= link_to 'Back to index', admin_restaurants_path, class: "btn btn-default" %>

      <%= link_to "Edit", edit_admin_restaurant_path(@restaurant.id), class: "btn btn-default" %>
    </div>

  </div>
</div>