config/routes.rb
Rails.application.routes.draw do
  # 透過 devise 實現使用者註冊，登入，管理
  devise_for :users

  # 前台餐廳 routes
  resources :restaurants, only: [:index, :show] do
    # for 餐廳評論
    resources :comments, only: [:create, :destroy]

    collection do
      # 瀏覽所有餐廳的最新動態
      get :feeds

      # TOP 10 Ranking restaurants
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end

    # 收藏與取消收藏餐廳功能
    member do
      post :favorite
      post :unfavorite
    end

  end

  root "restaurants#index"

  resources :categories, only: [:show]

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end

  # for 追蹤記錄，followships#create, followships#destroy
  resources :followships, only: [:create, :destroy]

  # for 交友記錄
  resources :friendships, only: [:create, :destroy]

  # 後台 routes
  namespace :admin, path: "akjdhkajsdh" do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # A restaurant belongs to specific category.
  belongs_to :category

  # A restaurant has_many comments.
  # 當 restaurant 物件被刪除時，同時刪除依賴的 comments
  has_many :comments, dependent: :destroy

  # 餐廳被很多使用者收藏，餐廳有很多收藏者
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  # 設定 name 欄位爲必填
  validates_presence_of :name

  # 掛載 carrierwave upload for upload image
  mount_uploader :image, PhotoUploader

  # for favorite restaurant check
  def is_favorited?(user)
    # 如果這家餐廳有被該使用者收藏，回傳 True
    self.favorited_users.include?(user)
  end

end

app/controllers/admin/restaurants_controller.rb
class Admin::RestaurantsController < Admin::BaseAdminController
  before_action :find_restaurant, only: [:show, :edit, :update, :destroy]

  def index
    # @restaurants = Restaurant.all
    # use Kaminari
    @restaurants = Restaurant.page(params[:page]).per(10)
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    if @restaurant.save
      flash[:notice] = "Restaurant was successfully created."
      redirect_to admin_restaurants_path
    else
      flash.now[:alert] = "Restaurant was failed to create!"
      render :new
    end
  end

  def show
    # 將此段程式碼另外宣告成 private method : find_restaurant
    # @restaurant = Restaurant.find(params[:id])
  end

  def edit
    # @restaurant = Restaurant.find(params[:id])
  end

  def update
    if @restaurant.update(restaurant_params)
      flash[:notice] = "Restaurant data was successfully updated."
      redirect_to admin_restaurant_path(@restaurant.id)
    else
      flash.now[:alert] = "Restaurant was failed to update!"
      render :edit
    end
  end

  def destroy
    flash[:alert] = "#{@restaurant.name} was deleted!"
    @restaurant.destroy
    redirect_to admin_restaurants_path
  end

  private
  def restaurant_params
    params.require(:restaurant).permit(:name, :opening_hours, :tel, :address, :description, :image, :category_id)
  end

  def find_restaurant
    @restaurant = Restaurant.find(params[:id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.page(params[:page]).per(9)
    @categories = Category.all
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    # 新增使用者評論
    @comment = Comment.new
  end

  # for 所有餐廳的最新動態
  def feeds
    @recent_restaurants = Restaurant.order(created_at: :desc).limit(10)
    @recent_comments = Comment.order(created_at: :desc).limit(10)
  end

  # for 每間餐廳的 dashboard (儀表板)
  def dashboard
    @restaurant = Restaurant.find(params[:id])
  end

  # 收藏餐廳與取消收藏餐廳
  ## POST /restaurant/:id/favorite
  def favorite
    @restaurant = Restaurant.find(params[:id])

    # Rails 會判斷需要的外鍵資訊
    @restaurant.favorites.create!(user: current_user)
    # 上一行結果與 @restaurant.favorites.create!(user_id: current_user.id) 結果一致

    # 導回上一頁
    redirect_back(fallback_location: root_path)
  end

  ## POST /restaurant/:id/unfavorite
  def unfavorite
    @restaurant = Restaurant.find(params[:id])
    favorites = Favorite.where(restaurant_id: @restaurant.id, user_id: current_user.id)
    # favorites = Favorite.where(restaurant: @restaurant, user: current_user)

    favorites.destroy_all

    redirect_back(fallback_location: root_path)
  end

  # for TOP 10 人氣餐廳
  ## GET /restaurants/ranking
  def ranking
    # 用 favorites_count 升冪排序，只取前十筆
    @restaurants = Restaurant.order(favorites_count: :desc).first(10)
  end

end

app/helpers/admin/restaurants_helper.rb
module Admin::RestaurantsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/dashboard.erb
<div class="container">
  <h1><%= @restaurant.name %>'s Dashboard</h1>
  <hr>
  <ul>
    <li>有 <%= @restaurant.comments.count %> 筆評論。 </li>
    <li>平均價位：$？？？</li>
    <li>有 ？？ 人收藏這家餐廳。</li>
  </ul>

  <%= link_to "返回 #{@restaurant.name} 餐廳", restaurant_path(@restaurant.id), class:"btn btn-default" %>
</div>

app/views/restaurants/feeds.html.erb
<div class="container">
  <%= render partial: "shared/restaurant_nav_bar" %>
  
  <div class="col-md-12">
    <h1>餐廳最新動態</h1>
  </div>


  <div class="col-md-6">
    <div class="panel panel-default">
      <div class="panel-heading">
        <h3 class="panel-title">最新餐廳</h3>
      </div>

      <div class="panel-body">
        <!-- panel content -->
        <% @recent_restaurants.each do |restaurant| %>
          <h4><%= link_to restaurant.name, restaurant_path(restaurant.id) %></h4>
          <p><%= restaurant.category.name %></p>
          <p><%= restaurant.description %></p>
          <hr>
        <% end %>
      </div>

    </div>

  </div>

  <div class="col-md-6">
    <div class="panel panel-success">
      <div class="panel-heading">
        <h3 class="panel-title">最新評論</h3>
      </div>

      <div class="panel-body">
        <% @recent_comments.each do |comment| %>
          <h4><%= link_to comment.restaurant.name, restaurant_path(comment.restaurant.id) %></h4>
          <p><%= comment.content %></p>
          <p>by <%= link_to comment.user.name, user_path(comment.user) %></p>
          <hr>
        <% end %>
      </div>
    </div>

  </div>
</div>

app/views/restaurants/index.html.erb
<div class="container">
  <div class="row">
    <%= render partial: "shared/restaurant_nav_bar" %>
    <br>

    <ul class="nav nav-pills nav-pills-center">
      <li role="presentation" class="active"><%= link_to "全部餐廳", root_path %></li>
      <% @categories.each do |category| %>
        <li role="presentation"><%= link_to category.name, category_path(category.id) %></li>
      <% end %>
    </ul>

    <br>

    <!-- 利用跟餐廳分類共用的局部樣板 -->
    <%= render partial: "shared/restaurant_list" %>

  </div>
</div>

app/views/restaurants/ranking.html.erb
<div class="container">
  <%= render partial: "shared/restaurant_nav_bar" %>
  
  <div class="col-md-12">
      <h4>TOP10 人氣餐廳 <small> (用收藏數排列) </small></h4>
    <hr>

    <!-- 已經整理好的前十間餐廳資料 -->
    <% @restaurants.each do |restaurant| %>
      <div class="ranking">
        <div class="col-md-4">
          <!-- 相片 -->
          <div class="ranking_img">
            <%= image_tag restaurant.image, class: "img-responsive center-block ranking " %>
          </div>
        </div>

        <div class="col-md-8 content">
          <!-- 餐廳名稱 -->
          <h4>
            <%= restaurant.name %>

            <!-- 收藏數 -->
            <p class="label label-default">收藏數：<%= restaurant.favorites_count %></p>
          </h4>

          <!-- 餐廳描述 -->
          <p><%= truncate(restaurant.description, length: 150) %></p>

          <div class="pull-buttom">
            <!-- show 按鈕 -->
            <%= link_to "Show", restaurant_path(restaurant.id), class: "btn btn-primary" %>

            <!-- favortie 按鈕 -->
            <%= render partial: "shared/favorite", locals: {restaurant: restaurant}%>
          </div>

        </div>

        <div class="clearfix"></div>

      </div>
    <% end %>
  </div>
</div>

app/views/restaurants/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12">
      <h1><%= @restaurant.name %></h1>
      <h4>
        [<%= @restaurant.category.name %>]
        <p class="pull-right">收藏人數：<%= @restaurant.favorites_count %></p>
      </h4>
    </div>

    <div class="col-md-4">
      <%= image_tag @restaurant.image, class: "img-responsive center-block" %>
      <br>
      <div class="well">
        <ul class="list-unstyled">
          <li><strong>Opening Hour:</strong> <%= @restaurant.opening_hours %></li>
          <li><strong>Tel:</strong> <%= @restaurant.tel %></li>
          <li><strong>Address:</strong> <%= @restaurant.address %></li>
        </ul>
      </div>
    </div>

    <div class="col-md-8">
      <%= simple_format @restaurant.description %>
      <hr>

      <!-- for dashboard -->
      <%= link_to "Dashboard", dashboard_restaurant_path(@restaurant.id), class:"btn btn-default" %>

      <!-- for favorite -->
      <%= render partial: "shared/favorite", locals: {restaurant: @restaurant}%>
      
      <div class="pull-right">
        <%= link_to "返回首頁", restaurants_path, class: "btn btn-default" %>
      </div>
    </div>

    <div class="clearfix"></div>

  </div>
</div>

<!-- for user comment -->
<div class="container">
  <div class="row">

    <!-- 顯示留言 -->
    <% @restaurant.comments.each do |comment| %>
    <div>
      <h4><%= comment.user.name %></h4>
      <p><%= simple_format comment.content %></p>
      <p class="text-muted">
        <em><%= comment.created_at.strftime("%Y-%m-%d")
     %></em>

        <% if current_user.admin? %>
          <%= link_to "Delete", restaurant_comment_path(@restaurant, comment), method: :delete %>
        <% end %>
      </p>

    </div>
    <% end %>

    <!-- 新增評論表單 -->
    <%= form_for [@restaurant, @comment] do |f| %>
      <div class="form-group">
        <%= f.text_area :content, placeholder: "請留言", class: "form-control" %>
      </div>

      <div class="form-group">
        <%= f.submit class: "btn btn-primary" %>
        <%= f.button "Clear Comment", type: :reset, class: "btn btn-default" %>
      </div>
    <% end %>

  </div>
</div>