config/routes.rb
Rails.application.routes.draw do
  # 透過 devise 實現使用者註冊，登入，管理
  devise_for :users

  # 前台餐廳 routes
  resources :restaurants, only: [:index, :show] do
    # for 餐廳評論
    resources :comments, only: [:create, :destroy]

    collection do
      # 瀏覽所有餐廳的最新動態
      get :feeds

      # TOP 10 Ranking restaurants
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end

    # 收藏與取消收藏餐廳功能
    member do
      post :favorite
      post :unfavorite
    end

  end

  root "restaurants#index"

  resources :categories, only: [:show]

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end

  # for 追蹤記錄，followships#create, followships#destroy
  resources :followships, only: [:create, :destroy]

  # for 交友記錄
  resources :friendships, only: [:create, :destroy]

  # 後台 routes
  namespace :admin, path: "akjdhkajsdh" do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/category.rb
class Category < ApplicationRecord
  # Let user must input category name
  validates_presence_of :name

  # A category has many restaurants.
  # 如果分類下已有餐廳，就不允許刪除分類 (並於執行刪除時拋出 error message)
  has_many :restaurants, dependent: :restrict_with_error
end

app/controllers/admin/categories_controller.rb
class Admin::CategoriesController < Admin::BaseAdminController
  # find category id before action !
  before_action :find_category, only: [:update, :destroy]

  def index
    @categories = Category.all

    # For new or edit Category
    if params[:id]
      @category = Category.find(params[:id])
    else
      @category = Category.new
    end

  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:notice] = "Category was successfully created."
      redirect_to admin_categories_path
    else
      flash[:notice] = "Category was failed to create."
      @categories = Category.all
      render :index
    end
  end

  def update
    # 有 before_action 先用 id 找 @category

    if @category.update(category_params)
      flash[:notice] = "Category data was successfully updated."
      redirect_to admin_categories_path
    else
      flash.now[:alert] = "Category was failed to update!"
      @categories = Category.all
      render :index
    end
  end

  def destroy
    # 有 before_action 先用 id 找 @category
    # 已經設定 dependency，如果 category 底下有關聯的 restaurant，會無法刪除且會有錯誤提示訊息。
    if @category.destroy
      flash[:notice] = "Category was successfully delete!"
    else
      flash[:alert] = @category.errors.full_messages.to_sentence
    end

    # 請注意目前這種刪法，會讓關聯的餐廳資料表顯示異常(缺少餐廳欄位資料)
    # @category.destroy
    # flash[:alert] = "Category was successfully deleted."

    redirect_to admin_categories_path
  end

  private
  def category_params
    params.require(:category).permit(:name)
  end

  def find_category
    @category = Category.find(params[:id])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    # 找出該分類底下的餐廳
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/helpers/admin/categories_helper.rb
module Admin::CategoriesHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/admin/categories/index.html.erb
<div class="container">

  <h1>餐廳分類總表</h1>
  <div>
    <%= link_to 'Restaurant', admin_restaurants_path %> |
    <%= link_to 'Category', admin_categories_path %>
  </div>

  <div class="row">

    <div class="col-md-12">

      <div>
        <div class="form-inline">
          <%= form_for [:admin, @category] do |f| %>
            <div class="form-group">
              <%= f.text_field :name, placeholder: "Category Name", class: "form-control" %>
            </div>
            <%= f.submit class: "btn btn-primary" %>
            <!-- add user create error message hint. -->
            <% if @category.errors.any? %>
              <%= @category.errors.full_messages.to_sentence %>
            <% end %>
          <% end %>

        </div>
      </div>
      <br>
      <table class="table table-striped table-bordered">
        <thead>
          <tr>
            <th>Primary Key(ID)</th>
            <th>Category Name</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody>
          <% @categories.each do |category| %>
          <tr>
            <th scope="row"><%= category.id %></th>
            <td><%= category.name %></td>
            <td>

              <!-- 記得是在首頁編輯 -->
              <%= link_to 'Edit', admin_categories_path(id: category.id) %>
              <%= link_to 'Delete', admin_category_path(category.id), method: :delete, data: { confirm: "Are you sure?"} %>

            </td>
          </tr>
          <% end %>
        </tbody>
      </table>

      <div class="text-center">
        <!-- paginate 是kaminari的hepler，可以幫我們產出分頁按鈕的html -->
        <%# paginate @categories %>
      </div>

    </div>

  </div>
</div>