config/routes.rb
Rails.application.routes.draw do
  # 透過 devise 實現使用者註冊，登入，管理
  devise_for :users

  # 前台餐廳 routes
  resources :restaurants, only: [:index, :show] do
    # for 餐廳評論
    resources :comments, only: [:create, :destroy]

    collection do
      # 瀏覽所有餐廳的最新動態
      get :feeds

      # TOP 10 Ranking restaurants
      get :ranking
    end

    # 瀏覽個別餐廳的 Dashboard
    member do
      get :dashboard
    end

    # 收藏與取消收藏餐廳功能
    member do
      post :favorite
      post :unfavorite
    end

  end

  root "restaurants#index"

  resources :categories, only: [:show]

  resources :users, only: [:index, :show, :edit, :update] do
    member do
      get :friend_list
    end
  end

  # for 追蹤記錄，followships#create, followships#destroy
  resources :followships, only: [:create, :destroy]

  # for 交友記錄
  resources :friendships, only: [:create, :destroy]

  # 後台 routes
  namespace :admin, path: "akjdhkajsdh" do
    resources :restaurants
    resources :categories
    root "restaurants#index"
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # Let user must input category name
  validates_presence_of :name

  # A category has many restaurants.
  # 如果分類下已有餐廳，就不允許刪除分類 (並於執行刪除時拋出 error message)
  has_many :restaurants, dependent: :restrict_with_error
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :user
  belongs_to :restaurant
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user

  # counter_cache 可以自動回傳 size method 的結果(計算關聯物件的數量)
  # 並把這個結果更新在關聯 Model 的欄位：{table_name}_count
  # 所以在這邊就會是：favorites_count
  belongs_to :restaurant, counter_cache: true
end

app/models/followship.rb
class Followship < ApplicationRecord
  # 每一筆追蹤記錄，屬於發出追蹤的使用者。
  belongs_to :user

  # 每一筆追蹤記錄，屬於被追蹤的使用者。
  belongs_to :follow_target, class_name: "User"

  # 在同一個 user_id 下，每個 follow_target_id 都是獨立的。
  validates :follow_target_id, uniqueness: { scope: :user_id }
end

app/models/friendship.rb
class Friendship < ApplicationRecord
  belongs_to :user

  # 朋友關係也屬於
  # belongs_to(:friend_target, class_name: "User", foreign_key: "friend_target_id", primary_key: "id")
  belongs_to :friend_target, class_name: "User"

  # 對於同一個 user_id 下，不會有重複的 friend_target_id
  validates :friend_target_id, uniqueness: {scope: :user_id}
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  # A restaurant belongs to specific category.
  belongs_to :category

  # A restaurant has_many comments.
  # 當 restaurant 物件被刪除時，同時刪除依賴的 comments
  has_many :comments, dependent: :destroy

  # 餐廳被很多使用者收藏，餐廳有很多收藏者
  has_many :favorites, dependent: :destroy
  has_many :favorited_users, through: :favorites, source: :user

  # 設定 name 欄位爲必填
  validates_presence_of :name

  # 掛載 carrierwave upload for upload image
  mount_uploader :image, PhotoUploader

  # for favorite restaurant check
  def is_favorited?(user)
    # 如果這家餐廳有被該使用者收藏，回傳 True
    self.favorited_users.include?(user)
  end

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # 讓使用者在註冊時一定要寫名字
  validates_presence_of :name

  # User has_many comments.
  # 如果 User 已有評論，就不允許刪除帳號 (刪除時拋出 Error)
  has_many :comments, dependent: :restrict_with_error

  # 實現多對多關聯
  has_many :commented_restaurants, through: :comments, source: :restaurant

  # 使用者收藏很多餐廳的多對多關聯
  has_many :favorites, dependent: :destroy
  has_many :favorited_restaurants, through: :favorites, source: :restaurant

  # for 追蹤使用者
  # 一個使用者有很多追蹤記錄
  has_many :followships, dependent: :destroy

  # 透過追蹤記錄，使用者有很多追蹤目標
  has_many :follow_targets, through: :followships

  # 設定反向追蹤記錄，找出追隨使用者的有哪些人
  # 先找出追蹤記錄
  has_many :inverse_followships, class_name: "Followship", foreign_key: "follow_target_id"

  # 找出追蹤者的資料
  has_many :followers, through: :inverse_followships, source: :user

  # For 交友記錄 (仿追蹤使用者)
  # 一個使用者有很多交友記錄
  has_many :friendships, dependent: :destroy

  # 透過交友記錄，使用者有很多朋友
  # has_many :friend_tagets, through: :friendships, source: :friend_target
  has_many :friend_targets, through: :friendships

  # 找出反向交友記錄，其他使用者將我加入好友的記錄
  has_many :inverse_friendships, class_name: "Friendship", foreign_key: "friend_target_id"

  # 找出將我加入好友的使用者
  has_many :inverse_friends, through: :inverse_friendships, source: :user

  def all_friends
    @my_all_friends = (self.friend_targets + self.inverse_friends).uniq
  end

  # for authenticate_admin method check role column value
  def admin?
    return self.role == "admin"
  end

  # 檢查追蹤使用者記錄是否存在
  def is_followed?(target_user)
    self.follow_targets.include?(target_user)
  end

  # 檢查交友關係是否存在
  def is_friend?(target_user)
    self.friend_targets.include?(target_user)
  end

  # 掛載 carrierwave upload for upload image
  mount_uploader :avatar, PhotoUploader
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # protect_from_forgery 用途待確認，記得只要不是 GET ，其他 VERB 一律要求要有 token，可避免某種攻擊
  protect_from_forgery with: :exception

  # add devise before filter to add parameters to User
  before_action :configure_permitted_parameters, if: :devise_controller?

  # 所有 action 先進行登入驗證才能執行
  before_action :authenticate_user!

  # Devise 客製化屬性
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def show
    @categories = Category.all
    @category = Category.find(params[:id])
    # 找出該分類底下的餐廳
    @restaurants = @category.restaurants.page(params[:page]).per(9)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    # 帶入 :restaurant_id 確認餐廳物件，觀察 rails routes restaurant_comments 的 URI pattern
    @restaurant = Restaurant.find(params[:restaurant_id])

    # Strong Parameters 驗證
    @comment = @restaurant.comments.build(comment_params)

    # 取得另一個 FK：讓現在登入的使用者爲評論的使用者
    @comment.user = current_user
    @comment.save!

    redirect_to restaurant_path(@restaurant.id)
  end

  def destroy
    if current_user.admin?
      # 先找到目前瀏覽的餐廳，因爲待會把留言刪了就沒辦法找到本來在瀏覽哪個餐廳了
      @restaurant = Restaurant.find(params[:restaurant_id])

      @comment = Comment.find(params[:id])
      @comment.destroy

      # 重新導向 到 當前的餐廳 show 頁面
      redirect_to restaurant_path(@restaurant.id)
    end
  end

  private
  def comment_params
    params.require(:comment).permit(:content)
  end
end

app/controllers/followships_controller.rb
class FollowshipsController < ApplicationController
  def create
    @followship = current_user.followships.build(follow_target_id: params[:follow_target_id])

    if @followship.save
      flash[:notice] = "Successfully followed."
      redirect_back(fallback_location: root_path)
    else
      flash[:alert ] = @followship.errors.full_messages.to_sentence
      redirect_back(fallback_location: root_path)
    end
  end

  def destroy
    @followship = current_user.followships.where(follow_target_id: params[:id]).first
    @followship.destroy
    flash[:notice] = "Followship destroyed!"
    redirect_back(fallback_location: root_path)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, only: [:show, :edit, :update]

  # for followships
  def index
    @users = User.all
  end

  def show
    # before_action :find_user
    # 使用者評論過的餐廳，並去掉重複的
    @commented_restaurants = @user.commented_restaurants.uniq
  end

  def edit
    # find_user

    # 讓使用者無法進入其他使用者的編輯頁面
    if @user == current_user
      # allow to edit
    else
      redirect_to user_path(@user.id)
    end
  end

  def update
    # find_user
    if @user.update(user_params)
      flash[:notice] = "User data was successfully updated."
      redirect_to user_path(@user.id)
    else
      flash.now[:alert] = "User was failed to update!"
      render :edit
    end
  end

  def friend_list
    
  end

  private
  # for before_action
  def find_user
    @user = User.find(params[:id])
    return @user
  end

  # for strong parameters
  def user_params
    params.require(:user).permit(:name, :intro, :avatar)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/followships_helper.rb
module FollowshipsHelper
end

app/helpers/friendships_helper.rb
module FriendshipsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RestaurantForum</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <!-- 使用者工具列(導覽列)： -->
    <nav class="navbar navbar-default">
      <div class="container-fluid">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <!-- <a class="navbar-brand" href="#">Brand</a> -->
          <%= link_to "餐廳評論網", root_path, class: "navbar-brand" %>
        </div>

        <!-- Collect the nav links, forms, and other content for toggling -->
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">

          <!-- pull-right 跟 navbar-right 似乎都能把元素往右推，順序就是從右邊數過來 -->
          <ul class="nav navbar-nav navbar-right">

            <!-- 所以建立按鈕/連結地方是就是透過沒有數字的清單項目 <li> 放連結 </li> -->
            <% if current_user %>
              <!-- 文字內容需要要另外處理，不然似乎套不到導覽列的格式，用 <li></li> 也可以 -->
              <p class="navbar-text">Hi, <%= current_user.email %></p>

              <% if current_user.admin? %>
                <li><%= link_to 'Admin後台', admin_restaurants_path %></li>
              <% end %>

              <li>
                <%= link_to "User Profile", user_path(current_user.id) %>
              </li>

              <li>
                <%= link_to('修改密碼', edit_user_registration_path) %>
              </li>
              <li>
                <%= link_to('登出', destroy_user_session_path, method: :delete) %>
              </li>

            <% else %>
              <li>
                <%= link_to('註冊', new_user_registration_path) %>
              </li>
              <li>
                <%= link_to('登入', new_user_session_path) %>
              </li>
            <% end %>
          </ul>
          <!-- 這邊學習了，果然需要在後面這邊註明 -->
        </div><!-- /.navbar-collapse -->
      </div><!-- /.container-fluid -->
    </nav>

    <!-- 加入 create/update action 的 flash message -->
    <% if flash[:notice] %>
      <div class="alert alert-warning alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= alert %>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/shared/_favorite.html.erb
<!-- for favorite button partial -->
<% if restaurant.is_favorited?(current_user) %>
  <%= link_to "Unfavorite", unfavorite_restaurant_path(restaurant.id), method: :post, class: "btn btn-info", data: { disable_with: "Waiting..." } %>
<% else %>
  <%= link_to "Favorite", favorite_restaurant_path(restaurant.id), method: :destroy, class: "btn btn-primary", data: { disable_with: "Waiting..." } %>
<% end %>

app/views/shared/_follow.html.erb
<% if current_user.is_followed?(target_user) %>
  <%= link_to "Unfollow", followship_path(target_user.id), method: :delete, class: "btn btn-default" %>
<% else %>
  <%= link_to "Follow", followships_path(follow_target_id: target_user.id), method: :post, data: { disable_with: "Waiting..." }, class: "btn btn-success" %>
<% end %>

<% if current_user.is_friend?(target_user) %>
  <%= link_to "Unfriend", friendship_path(target_user.id), method: :delete, class: "btn btn-default" %>
<% else %>
  <%= link_to "Friend", friendships_path(friend_target_id: target_user.id), method: :post, data: { disable_with: "Waiting..." }, class: "btn btn-primary" %>
<% end %>

app/views/shared/_restaurant_list.html.erb
<!-- restaurants list，有多寫restaurant-item的class style -->
<% @restaurants.each do |restaurant| %>
  <div class="col-sm-6 col-md-4">
    <div class="restaurant-item">

      <div class="caption">

        <%= link_to restaurant_path(restaurant.id) do %>
          <%= image_tag restaurant.image, class: "center-block" %>

          <h3>
            <%= restaurant.name %>

            <!-- for favorite button -->
            <p class="pull-right">
              <%= render partial: "shared/favorite", locals: {restaurant: restaurant} %>
            </p>
          </h3>
        <% end %>

        <p class="label label-default"><%= restaurant.category.name %></p>
        <p><%= truncate(restaurant.description, length: 80) %></p>
      </div>
    </div>
  </div>
<% end %>

<!-- 有generate kaminari paginate bootstrap style -->
<div class="text-center">
  <%= paginate @restaurants %>
</div>

app/views/shared/_restaurant_nav_bar.html.erb
<div class="container">
  <div class="row">
    <ul class="nav nav-tabs">
      <li role="presentation" class="<%= "active" if current_page?(restaurants_path) || current_page?(root_path) %>">
        <%= link_to "首頁", restaurants_path %>
      </li>

      <li role="presentation" class="<%= "active" if current_page?(feeds_restaurants_path) %>">
        <%= link_to "最新消息", feeds_restaurants_path %>
      </li>

      <li role="presentation" class="<%= "active" if current_page?(ranking_restaurants_path) %>">
        <%= link_to "TOP10 人氣餐廳", ranking_restaurants_path %>
      </li>

      <li role="presentation" class="<%= "active" if current_page?(users_path) %>">
        <%= link_to "美食獵人", users_path %>
      </li>

      <li role="presentation" class="<%= "active" if current_page?(friend_list_user_path(current_user.id)) %>">
        <%= link_to "我的好友", friend_list_user_path(current_user.id) %>
      </li>
    </ul>
  </div>
</div>